-- Restore the EXTERIOR / INTERIOR / BRAKE checklist as the active QC-In master.
--
-- 0060_qc_truck_checklist replaced it with a 13-category truck Preventative-
-- Maintenance sheet. The QC-In wizard is built around exactly three categories,
-- so on any database where 0060 ran, every checklist step renders an EMPTY list
-- and the inspector cannot record anything. This restores the original sheet.
--
-- REVERSIBLE BY DESIGN — the truck rows are DEACTIVATED, never deleted:
--   * to switch back to the truck sheet, flip is_active on the two groups.
--   * historical inspections are untouched either way; qc_inspection_items are
--     snapshots taken at inspection time, not references to this master. Any
--     inspection already created from the truck sheet keeps its truck items.
--
-- Idempotent: re-running re-asserts the same active/inactive split. Relies on
-- the unique index on item_code so a re-run updates rather than duplicates.

-- 1) Park the truck sheet. Kept in the table so nothing is lost.
UPDATE "qc_checklist_templates"
   SET "is_active" = false, "updated_at" = now()
 WHERE "category" NOT IN ('EXTERIOR', 'INTERIOR', 'BRAKE');

-- 2) Restore the car checklist (115 items: 45 EXTERIOR, 31 INTERIOR, 39 BRAKE).
INSERT INTO "qc_checklist_templates"
  ("category","sub_category","item_code","item_label","sort_order","is_active")
VALUES
  ('BRAKE','Front Axle Brakes','BRK-FAB-01','Brake boosters and pipes — Left',1,true),
  ('BRAKE','Front Axle Brakes','BRK-FAB-02','Brake boosters and pipes — Right',2,true),
  ('BRAKE','Front Axle Brakes','BRK-FAB-03','Brake lining / disc thickness — Left',3,true),
  ('BRAKE','Front Axle Brakes','BRK-FAB-04','Brake lining / disc thickness — Right',4,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-01','Shocks & mountings — Left',5,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-02','Shocks & mountings — Right',6,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-03','Brake boosters and pipes — Left',7,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-04','Brake boosters and pipes — Right',8,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-05','"S" cam system — Left',9,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-06','"S" cam system — Right',10,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-07','Trunnion bearing',11,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-08','Suspension mountings',12,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-09','Torque rods — Left',13,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-10','Torque rods — Right',14,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-11','Springs / air bags — Left',15,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-12','Springs / air bags — Right',16,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-13','Lining / disc thickness — Left',17,true),
  ('BRAKE','Forward Rear Axle Brakes','BRK-FRB-14','Lining / disc thickness — Right',18,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-01','Shocks & mountings — Left',19,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-02','Shocks & mountings — Right',20,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-03','Brake boosters and pipes — Left',21,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-04','Brake boosters and pipes — Right',22,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-05','"S" cam systems — Left',23,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-06','"S" cam systems — Right',24,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-07','Suspension mounts — Left',25,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-08','Suspension mounts — Right',26,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-09','Torque rods — Left',27,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-10','Torque rods — Right',28,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-11','Springs / air bags — Left',29,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-12','Springs / air bags — Right',30,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-13','Load sensing valve',31,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-14','Torque U bolts',32,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-15','Lining / disc thickness — Left',33,true),
  ('BRAKE','Rear Rear Axle / Tag Axle Brakes','BRK-RRB-16','Lining / disc thickness — Right',34,true),
  ('BRAKE','Air System','BRK-AIR-01','Trailer control valve',35,true),
  ('BRAKE','Air System','BRK-AIR-02','Height levelling valve',36,true),
  ('BRAKE','Air System','BRK-AIR-03','F & J coupling',37,true),
  ('BRAKE','Air System','BRK-AIR-04','Drain air tanks — check air leaks',38,true),
  ('BRAKE','Air System','BRK-AIR-05','Pipes, clamps & air leaks',39,true),
  ('EXTERIOR','Engine','EXT-ENG-01','Oil leaks',1,true),
  ('EXTERIOR','Engine','EXT-ENG-02','Fuel pipes condition and leaks',2,true),
  ('EXTERIOR','Engine','EXT-ENG-03','Injector pump throttle travel',3,true),
  ('EXTERIOR','Engine','EXT-ENG-04','Exhaust system',4,true),
  ('EXTERIOR','Engine','EXT-ENG-05','Air intake system',5,true),
  ('EXTERIOR','Engine','EXT-ENG-06','Oil filler tube',6,true),
  ('EXTERIOR','Engine','EXT-ENG-07','Dipstick and tube',7,true),
  ('EXTERIOR','Engine','EXT-ENG-08','All V belts',8,true),
  ('EXTERIOR','Engine','EXT-ENG-09','V belt tensioners',9,true),
  ('EXTERIOR','Engine','EXT-ENG-10','All clamps & hoses',10,true),
  ('EXTERIOR','Engine','EXT-ENG-11','Engine mountings — Front',11,true),
  ('EXTERIOR','Engine','EXT-ENG-12','Engine mountings — Rear',12,true),
  ('EXTERIOR','Cooling System','EXT-COOL-01','Pressure test cooling system',13,true),
  ('EXTERIOR','Cooling System','EXT-COOL-02','All clamps & hoses',14,true),
  ('EXTERIOR','Cooling System','EXT-COOL-03','Header tank and cap',15,true),
  ('EXTERIOR','Cooling System','EXT-COOL-04','Fan hub, blades and cowl',16,true),
  ('EXTERIOR','Cooling System','EXT-COOL-05','Radiator / intercooler condition',17,true),
  ('EXTERIOR','Rear of Cab','EXT-ROC-01','Battery box and supports',18,true),
  ('EXTERIOR','Rear of Cab','EXT-ROC-02','Cab mounting, locks & cab suspension — Left',19,true),
  ('EXTERIOR','Rear of Cab','EXT-ROC-03','Cab mounting, locks & cab suspension — Right',20,true),
  ('EXTERIOR','Rear of Cab','EXT-ROC-04','Cab jack system & oil level',21,true),
  ('EXTERIOR','Rear of Cab','EXT-ROC-05','Air drier system',22,true),
  ('EXTERIOR','Rear of Cab','EXT-ROC-06','Cat walk',23,true),
  ('EXTERIOR','Steering System','EXT-STR-01','Drop arm nut',24,true),
  ('EXTERIOR','Steering System','EXT-STR-02','Tie rod ends',25,true),
  ('EXTERIOR','Steering System','EXT-STR-03','Drag link joints',26,true),
  ('EXTERIOR','Steering System','EXT-STR-04','U-joint steering shaft',27,true),
  ('EXTERIOR','Steering System','EXT-STR-05','Power steering pipes and connections',28,true),
  ('EXTERIOR','Propshaft','EXT-PRP-01','Grease nipples — Front',29,true),
  ('EXTERIOR','Propshaft','EXT-PRP-02','Grease nipples — Rear',30,true),
  ('EXTERIOR','Propshaft','EXT-PRP-03','Slip joints — Front',31,true),
  ('EXTERIOR','Propshaft','EXT-PRP-04','Slip joints — Rear',32,true),
  ('EXTERIOR','Propshaft','EXT-PRP-05','U joints — Front',33,true),
  ('EXTERIOR','Propshaft','EXT-PRP-06','U joints — Rear',34,true),
  ('EXTERIOR','Propshaft','EXT-PRP-07','Cap bolts — Front',35,true),
  ('EXTERIOR','Propshaft','EXT-PRP-08','Cap bolts — Rear',36,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-01','Mounting bolts',37,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-02','5th wheel rubbers',38,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-03','Locking jaw and wear ring size',39,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-04','Handle & action',40,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-05','Fuel tank brackets',41,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-06','Spare wheel carrier',42,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-07','PTO pump fitment',43,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-08','Hydraulic tank and brackets',44,true),
  ('EXTERIOR','5th Wheel & Other','EXT-5WH-09','Hydraulic pipes and couplings',45,true),
  ('INTERIOR','Gearbox','INT-GBX-01','Gear lever, bush, control rods & adjustment',1,true),
  ('INTERIOR','Gearbox','INT-GBX-02','Front clevis pin (INT only)',2,true),
  ('INTERIOR','Gearbox','INT-GBX-03','G/box oil cooler',3,true),
  ('INTERIOR','Gearbox','INT-GBX-04','Bell housing bolts',4,true),
  ('INTERIOR','Gearbox','INT-GBX-05','Oil leaks',5,true),
  ('INTERIOR','Gearbox','INT-GBX-06','Output shaft play',6,true),
  ('INTERIOR','Gearbox','INT-GBX-07','Top cover oil leaks',7,true),
  ('INTERIOR','Gearbox','INT-GBX-08','Rear clevis pin (IH only)',8,true),
  ('INTERIOR','Gearbox','INT-GBX-09','G/box spring blade (if applicable)',9,true),
  ('INTERIOR','Forward Rear Axle & Diff','INT-FRA-01','Diff and 3rd diff lock operation',10,true),
  ('INTERIOR','Forward Rear Axle & Diff','INT-FRA-02','Input shaft play',11,true),
  ('INTERIOR','Forward Rear Axle & Diff','INT-FRA-03','Output shaft play',12,true),
  ('INTERIOR','Forward Rear Axle & Diff','INT-FRA-04','Oil leaks',13,true),
  ('INTERIOR','Rear Rear Axle & Diff / Tag Axle','INT-RRA-01','Input shaft play',14,true),
  ('INTERIOR','Rear Rear Axle & Diff / Tag Axle','INT-RRA-02','Oil leaks',15,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-01','Hub oil / grease leaks — Left',16,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-02','Hub oil / grease leaks — Right',17,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-03','U bolts — Left',18,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-04','U bolts — Right',19,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-05','Springs — Left',20,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-06','Springs — Right',21,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-07','Spring hanger & pins — Left',22,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-08','Spring hanger & pins — Right',23,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-09','Shocks & mountings — Left',24,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-10','Shocks & mountings — Right',25,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-11','King pin play — Left',26,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-12','King pin play — Right',27,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-13','Front bearing noise and play — Left',28,true),
  ('INTERIOR','Front Axle & Suspension','INT-FAS-14','Front bearing noise and play — Right',29,true),
  ('INTERIOR','Electrical','INT-ELC-01','Check instrument cluster',30,true),
  ('INTERIOR','Electrical','INT-ELC-02','Check all lights',31,true)
ON CONFLICT ("item_code") DO UPDATE SET
  "category"     = EXCLUDED."category",
  "sub_category" = EXCLUDED."sub_category",
  "item_label"   = EXCLUDED."item_label",
  "sort_order"   = EXCLUDED."sort_order",
  "is_active"    = true,
  "updated_at"   = now();
